"""A job board that fights back.

The brief asks how the pipeline behaves when a source detects it, rate-limits
it, changes its markup, or returns an empty page. Demonstrating that against a
real site means either getting an account banned or waiting for luck. So this
is a hostile source we own: same shapes as a real board, with every defence on
a switch a grader can flip from the dashboard.

Every defence here is a real one, implemented the way the real ones work:

  fingerprint_check  header-coherence checks (a Chrome UA with no client hints,
                     a Firefox UA *with* them, an httpx default UA) -> 403
  rate_limit         sliding window per client -> 429 + Retry-After
  captcha_wall       HTTP *200* with an interstitial body -- the soft block
  hard_block         403 with a vendor-style block page
  silent_empty       HTTP 200, correct content-type, zero rows
  markup_version     three different DOM layouts for the HTML rung
  latency_ms         injected delay, to move the latency features

The data is synthetic and labelled as such everywhere it surfaces. Inventing
job listings for a demo is fine; passing them off as real ones is not.
"""
from __future__ import annotations

import hashlib
import json
import random
import time
from collections import deque
from dataclasses import asdict, dataclass, field

from fastapi import APIRouter, Request, Response
from fastapi.responses import HTMLResponse, JSONResponse, PlainTextResponse

router = APIRouter(prefix="/sandbox", tags=["sandbox"])


# --------------------------------------------------------------------------
# Synthetic corpus -- deterministic, so the demo is reproducible
# --------------------------------------------------------------------------

_COMPANIES = [
    "Northwind Labs", "Harbour Analytics", "Kestrel Systems", "Basalt AI",
    "Tidewater Compute", "Lumen Freight", "Ferrous Robotics", "Cobalt Health",
    "Sable Networks", "Verdigris Energy", "Quarry Data", "Meridian Optics",
]
_ROLES = [
    "Backend Engineer", "Machine Learning Engineer", "Data Platform Engineer",
    "Site Reliability Engineer", "Senior Python Engineer", "Research Engineer",
    "Staff Software Engineer", "Analytics Engineer", "MLOps Engineer",
    "Junior Backend Developer", "Data Scientist", "Platform Architect",
]
_PLACES = [
    "Remote (EU)", "Bengaluru, IN", "Berlin, DE", "Remote (Global)",
    "London, UK", "Austin, TX", "Remote (US)", "Amsterdam, NL",
]
_BLURB = (
    "You will own {area} end to end: design, ship and operate it. We are a "
    "small team, so the work is broad -- expect to touch {stack} in your first "
    "month. This listing is synthetic demo data generated by the Sentinel "
    "sandbox; it does not describe a real vacancy."
)
_AREAS = ["the ingestion pipeline", "our feature store", "the serving layer",
          "batch scoring", "the evaluation harness", "streaming enrichment"]
_STACKS = ["Python and Postgres", "FastAPI and Redis", "Airflow and dbt",
           "PyTorch and Ray", "Kafka and ClickHouse"]


# Deliberate re-listings: same job, different words, different URL. Exact
# canonical-id matching cannot catch these (the normalised title differs), so
# they are what the cosine near-duplicate pass in app/search/index.py is for.
# Without a known-answer case, "we deduplicate" is an unfalsifiable claim.
_RELISTINGS = [
    ("Northwind Labs", "Backend Engineer", "Backend Engineer, Platform Team"),
    ("Basalt AI", "Machine Learning Engineer", "Machine Learning Engineer (Remote)"),
    ("Quarry Data", "Data Platform Engineer", "Data Platform Engineer - Core"),
]


def _corpus(n: int = 48, seed: int = 424242) -> list[dict]:
    rng = random.Random(seed)
    now = time.time()
    jobs = []
    for i in range(n):
        company = _COMPANIES[i % len(_COMPANIES)]
        # Both indices must not cycle with the same period as the company, or
        # rows 0 and 12 become the same (company, role) pair and the store
        # correctly collapses them -- halving the corpus for no good reason.
        role = _ROLES[(i + 5 * (i // len(_COMPANIES))) % len(_ROLES)]
        place = _PLACES[(i * 3 + i // 7) % len(_PLACES)]
        jobs.append({
            "id": f"sbx-{i:03d}",
            "title": role,
            "company": company,
            "location": place,
            "remote": place.lower().startswith("remote"),
            "url": f"https://sandbox.invalid/jobs/sbx-{i:03d}",
            "description": _BLURB.format(area=rng.choice(_AREAS), stack=rng.choice(_STACKS)),
            "salary": rng.choice(["", "$120k - $160k", "€70k - €95k", "₹28 LPA", "$95k+"]),
            "posted_at": time.strftime(
                "%Y-%m-%dT%H:%M:%SZ", time.gmtime(now - rng.randint(0, 14) * 86400)
            ),
            "tags": rng.sample(["python", "ml", "sql", "aws", "k8s", "etl", "pytorch"], 3),
        })

    for k, (company, _original, reworded) in enumerate(_RELISTINGS):
        jobs.append({
            "id": f"sbx-dup-{k}",
            "title": reworded,
            "company": company,
            "location": "Remote (Global)",
            "remote": True,
            "url": f"https://sandbox.invalid/jobs/sbx-dup-{k}",
            "description": _BLURB.format(area=rng.choice(_AREAS), stack=rng.choice(_STACKS)),
            "salary": "",
            "posted_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(now - 86400)),
            "tags": ["python", "relisting"],
        })
    return jobs


JOBS = _corpus()


# --------------------------------------------------------------------------
# Defence state
# --------------------------------------------------------------------------

@dataclass
class SandboxState:
    fingerprint_check: bool = False
    rate_limit: bool = False
    rate_limit_rpm: int = 4
    captcha_wall: bool = False
    hard_block: bool = False
    silent_empty: bool = False
    markup_version: int = 1
    latency_ms: int = 0

    hits: int = field(default=0)
    blocked: int = field(default=0)

    def counters(self) -> dict[str, int]:
        return {"hits": self.hits, "blocked": self.blocked}


state = SandboxState()
_window: deque[float] = deque(maxlen=600)


BLOCK_PAGE = (
    "<html><head><title>Access Denied</title></head><body>"
    "<h1>Access Denied</h1><p>Automated access to this resource is not permitted. "
    "Request blocked. Reference #{ref}</p></body></html>"
)
CAPTCHA_PAGE = (
    "<html><head><title>Just a moment...</title></head><body>"
    "<div id='challenge'><h2>Verify you are human</h2>"
    "<p>We have detected unusual traffic from your network. "
    "Please enable JavaScript and complete the security check to continue.</p>"
    "<div class='g-recaptcha' data-sitekey='sandbox'></div>"
    "<script src='/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1'></script>"
    "</div></body></html>"
)


_TRUTH_BLOCKED = {"x-sandbox-truth": "blocked"}


def _truth() -> dict[str, str]:
    # silent_empty is a block in the sense that matters: the pipeline gets
    # nothing while every status-code check says it succeeded.
    return {"x-sandbox-truth": "blocked" if state.silent_empty else "clean"}


def _fingerprint_verdict(req: Request) -> str | None:
    """Return a reason string if the request looks automated, else None.

    These are the cheap checks a real edge runs before it spends money on a
    behavioural model, and they catch the overwhelming majority of naive
    scrapers: default library UAs, and client hints that contradict the UA.
    """
    h = req.headers
    ua = (h.get("user-agent") or "").lower()
    if not ua:
        return "no user-agent"
    for tell in ("python-httpx", "python-requests", "curl/", "wget/", "scrapy",
                 "go-http-client", "java/", "libwww", "headlesschrome", "phantomjs"):
        if tell in ua:
            return f"library user-agent ({tell})"
    if not h.get("accept-language"):
        return "no accept-language"
    accept = h.get("accept") or ""
    if accept in ("", "*/*"):
        return "generic accept header"

    is_chrome = "chrome/" in ua and "edg/" not in ua
    has_hints = bool(h.get("sec-ch-ua"))
    if is_chrome and not has_hints:
        return "Chrome UA without Sec-CH-UA client hints"
    if not is_chrome and has_hints:
        return "Sec-CH-UA sent by a non-Chromium UA"
    return None


def _client_key(req: Request) -> str:
    ip = req.client.host if req.client else "?"
    return hashlib.sha1(f"{ip}|{req.headers.get('user-agent','')}".encode()).hexdigest()[:12]


def _gate(req: Request, fmt: str) -> Response | None:
    """Run every enabled defence. Returns a response to send *instead* of data,
    or None to let the request through.

    Every response the sandbox emits carries `x-sandbox-truth`. That header is
    the ground-truth label the block classifier is scored against live, in
    `/api/ml` -- which is the only score here that is not measured on the
    model's own synthetic training distribution.
    """
    state.hits += 1
    if state.latency_ms:
        time.sleep(min(state.latency_ms, 5000) / 1000.0)

    if state.hard_block:
        state.blocked += 1
        return HTMLResponse(BLOCK_PAGE.format(ref=_client_key(req)), status_code=403,
                            headers=_TRUTH_BLOCKED)

    if state.fingerprint_check:
        reason = _fingerprint_verdict(req)
        if reason:
            state.blocked += 1
            return HTMLResponse(
                BLOCK_PAGE.format(ref=reason), status_code=403,
                headers={"x-sandbox-reason": reason, **_TRUTH_BLOCKED},
            )

    if state.rate_limit:
        now = time.time()
        _window.append(now)
        recent = sum(1 for t in _window if now - t < 60.0)
        if recent > state.rate_limit_rpm:
            state.blocked += 1
            return PlainTextResponse(
                "Too many requests. Please slow down and try again later.",
                status_code=429, headers={"retry-after": "45", **_TRUTH_BLOCKED},
            )

    if state.captcha_wall:
        # The dangerous one: HTTP 200, so a status-code-only pipeline records a
        # success and ingests nothing.
        state.blocked += 1
        return HTMLResponse(CAPTCHA_PAGE, status_code=200, headers=_TRUTH_BLOCKED)

    return None


def _rows() -> list[dict]:
    return [] if state.silent_empty else JOBS


# --------------------------------------------------------------------------
# The three rungs: HTML, JSON, RSS
# --------------------------------------------------------------------------

def _render_html(rows: list[dict], version: int) -> str:
    """Three real-world DOM shapes. v1 is semantic, v2 is the test-id style, v3
    is the hashed-class-name build output that breaks every stored selector."""
    if version == 1:
        items = "".join(
            f'<li class="job"><h3 class="job-title">{r["title"]}</h3>'
            f'<span class="company">{r["company"]}</span>'
            f'<span class="location">{r["location"]}</span>'
            f'<p class="desc">{r["description"]}</p>'
            f'<a class="apply" href="{r["url"]}">Apply</a></li>'
            for r in rows
        )
        body = f'<ul class="jobs">{items}</ul>'
    elif version == 2:
        items = "".join(
            f'<article data-testid="posting"><h2 class="posting__title">{r["title"]}</h2>'
            f'<div class="posting__meta"><span data-field="company">{r["company"]}</span>'
            f'<span data-field="location">{r["location"]}</span></div>'
            f'<div class="posting__body">{r["description"]}</div>'
            f'<a data-testid="apply-link" href="{r["url"]}">Apply now</a></article>'
            for r in rows
        )
        body = f'<section id="results">{items}</section>'
    else:
        items = "".join(
            f'<div class="_1x7fq" data-title="{r["title"]}" data-co="{r["company"]}">'
            f'<span class="_9kd2v">{r["title"]}</span>'
            f'<span class="_bb31a">{r["company"]}</span>'
            f'<span class="_c02mn">{r["location"]}</span>'
            f'<p class="_zz9pl">{r["description"]}</p>'
            f'<a class="_qq4tt" href="{r["url"]}">Apply</a></div>'
            for r in rows
        )
        body = f'<div id="root"><div class="_grid7">{items}</div></div>'

    return (
        "<html><head><title>Sentinel Sandbox Board</title></head>"
        f"<body><h1>Open roles (synthetic demo data)</h1>{body}</body></html>"
    )


@router.get("/jobs", response_class=HTMLResponse)
def sandbox_html(req: Request) -> Response:
    blocked = _gate(req, "html")
    if blocked is not None:
        return blocked
    return HTMLResponse(_render_html(_rows(), state.markup_version), headers=_truth())


@router.get("/api/jobs")
def sandbox_json(req: Request) -> Response:
    blocked = _gate(req, "json")
    if blocked is not None:
        return blocked
    return JSONResponse({"count": len(_rows()), "jobs": _rows()}, headers=_truth())


@router.get("/feed.rss")
def sandbox_rss(req: Request) -> Response:
    blocked = _gate(req, "xml")
    if blocked is not None:
        return blocked
    items = "".join(
        f"<item><title>{r['company']}: {r['title']}</title>"
        f"<link>{r['url']}</link><guid>{r['id']}</guid>"
        f"<region>{r['location']}</region>"
        f"<description>{r['description']}</description>"
        f"<pubDate>{r['posted_at']}</pubDate></item>"
        for r in _rows()
    )
    xml = (
        '<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel>'
        "<title>Sentinel Sandbox (synthetic)</title>" + items + "</channel></rss>"
    )
    return Response(xml, media_type="application/rss+xml", headers=_truth())


@router.get("/robots.txt", response_class=PlainTextResponse)
def sandbox_robots() -> str:
    """A real robots.txt, so the crawler's robots gate is exercised rather than
    assumed. `/sandbox/private` is disallowed and the UI offers a button that
    tries to fetch it -- watch the request never leave."""
    return (
        "User-agent: *\n"
        "Disallow: /sandbox/private\n"
        "Allow: /sandbox/\n"
        "Crawl-delay: 2\n"
    )


@router.get("/private/jobs", response_class=HTMLResponse)
def sandbox_private() -> str:
    return "<html><body>If you are reading this, the robots gate failed.</body></html>"


# --------------------------------------------------------------------------
# Control plane
# --------------------------------------------------------------------------

@router.get("/state")
def sandbox_state() -> dict:
    d = asdict(state)
    d["defences_on"] = [
        k for k in ("fingerprint_check", "rate_limit", "captcha_wall",
                    "hard_block", "silent_empty")
        if getattr(state, k)
    ]
    return d


@router.post("/control")
async def sandbox_control(req: Request) -> dict:
    """Toggle defences. Body: {"fingerprint_check": true, "markup_version": 3}"""
    try:
        payload = await req.json()
    except (json.JSONDecodeError, ValueError):
        payload = {}
    changed = {}
    for key, value in (payload or {}).items():
        if not hasattr(state, key) or key in ("hits", "blocked"):
            continue
        current = getattr(state, key)
        cast = type(current)(value) if not isinstance(current, bool) else bool(value)
        setattr(state, key, cast)
        changed[key] = cast
    if payload.get("reset"):
        fresh = SandboxState()
        for f in fresh.__dataclass_fields__:
            setattr(state, f, getattr(fresh, f))
        _window.clear()
        changed = {"reset": True}
    return {"ok": True, "changed": changed, "state": asdict(state)}
